name: check workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: Build
        run: |
          make build-for-testing

      - name: Test
        run: |
          make test-without-building
